spring:
  profiles:
    active: ${PROFILE}
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    tomcat:
      max-active: 4
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update # change to create-drop or update in development, none in production
    show-sql: false # only for development, not recommended in production
  devtools:
    restart:
      log-condition-evaluation-delta: false